version: '3.8'

services:
  api:
    build: ./api
    volumes:
      - ./api/app:/code/app
      - shared-volume:/code/data
      - ./shared_utils:/code/shared_utils
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "8080:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
        - shared-network

  pangolin:
    build: ./pangolin
    volumes:
      - ./pangolin/app:/code/app
      - ./pangolin/main.py:/code/main.py
      - shared-volume:/code/data
      - ./shared_utils:/code/shared_utils
    command: python3 main.py
    depends_on:
      - api
      - rabbitmq
    networks:
      - shared-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - shared-network
    healthcheck:
      test: "exit 0"


  redis:
    image: redis:latest
    container_name: redisalg
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - shared-network


networks:
    shared-network:

volumes:
  redis-data:
  shared-volume: