version: '3.8'

services:
  api:
    build: ./api
    volumes:
      - ./api/app:/code/app
      - shared-volume:/code/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "8080:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
        - shared-network

  worker:
    build: ./worker
    volumes:
      - ./worker/app:/code/app
      - shared-volume:/code/app/data
    command: python3 app/main.py
    depends_on:
      - api
      - rabbitmq
      - cassandra
    networks:
      - shared-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - shared-network
    healthcheck:
      test: "exit 0"

  cassandra:
    image: cassandra:latest
    hostname: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - shared-network
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_DC=mydc
      - CASSANDRA_RACK=myrack
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]

networks:
    shared-network:

volumes:
  cassandra-data:
  shared-volume: