version: '3.8'

services:
  api:
    build: taskflowapi/api
    container_name: api
    volumes:
      - ./taskflowapi/api/app:/code/app
      - shared-volume:/code/data
      - ./taskflowapi/shared_utils:/code/shared_utils
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "8080:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
        - shared-network

  orchestrator:
    build: taskflowapi/orchestrator
    container_name: orchestrator
    volumes:
      - ./taskflowapi/orchestrator/app:/code/app
      - shared-volume:/code/app/data
      - ./taskflowapi/shared_utils:/code/app/shared_utils
      - ./algorithmworkers/config.py:/code/app/algorithms/config.py
    working_dir: /code/app
    command: bash -c "python3 main.py"
    depends_on:
      - api
      - rabbitmq
      - redis
    networks:
      - shared-network

  parser:
    build: taskflowapi/parser
    container_name: parser
    volumes:
      - ./taskflowapi/parser/app:/code/app
      - shared-volume:/code/app/data
      - ./taskflowapi/shared_utils:/code/app/shared_utils
    working_dir: /code/app
    command: bash -c "python3 main.py"
    depends_on:
      - api
      - rabbitmq
      - redis
      - orchestrator
      - pangolin
    networks:
      - shared-network

  pangolin:
    build: algorithmworkers/pangolin
    volumes:
      - ./algorithmworkers/pangolin/app:/code/app
      - ./algorithmworkers/pangolin/main.py:/code/main.py
      - shared-volume:/code/data
    command: python3 main.py
    depends_on:
      - api
      - rabbitmq
    networks:
      - shared-network

  spip:
    build: algorithmworkers/spip_mock
    volumes:
      - ./algorithmworkers/spip_mock/app:/code/app
      - ./algorithmworkers/spip_mock/alg:/code/alg
      - ./algorithmworkers/spip_mock/main.py:/code/main.py
      - shared-volume:/code/data
    command: python3 main.py
    depends_on:
      - api
      - rabbitmq
    networks:
      - shared-network

  spip:
    build: ./spip
    volumes:
      - shared-volume:/code/data
      - ./spip/perf_tests:/usr/src/app/SPiP/perf_tests
    command: tail -f /dev/null
    depends_on:
      - api
      - rabbitmq
    networks:
      - shared-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - shared-network
    healthcheck:
      test: "exit 0"


  redis:
    image: redis:latest
    container_name: redisalg
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - shared-network


networks:
    shared-network:

volumes:
  redis-data:
  shared-volume: